interface Images {
  [x: string]: string;
}

export const regionImages: Images = {
  AncientTomb: require("./AncientTomb.png"),
  ArcaneTower: require("./ArcaneTower.png"),
  GapingMaw: require("./GapingMaw.png"),
  Shrine: require("./Shrine.png"),
  CommandPost: require("./CommandPost.png"),
  Monastery: require("./Monastery.png"),
  Inn: require("./Inn.png"),
  Academy: require("./Academy.png"),
  CurioShoppe: require("./CurioShoppe.png"),
  Menagerie: require("./Menagerie.png"),
  Fort: require("./Fort.png"),
  Library: require("./Library.png"),
  HolySpire: require("./HolySpire.png"),
  TempleOfLegends: require("./TempleOfLegends.png"),
  Villages: require("./Villages.png"),
  HiddenRuins: require("./HiddenRuins.png"),
  BuildingSite: require("./BuildingSite.png"),
  Chronogate: require("./Chronogate.png"),
  Farm: require("./Farm.png"),
  MercenaryCamp: require("./MercenaryCamp.png"),
  Obelisk: require("./Obelisk.png"),
  Sanctum: require("./Sanctum.png"),
  TempleRuins: require("./TempleRuins.png"),
  TriflesNTrinkets: require("./TriflesNTrinkets.png"),
  WellOfWishes: require("./WellOfWishes.png"),
  WhiteRavenInn: require("./WhiteRavenInn.png"),
  BazaarOfSol: require("./BazaarOfSol.png"),
  SacredStones: require("./SacredStones.png"),
  Jewelcrafter: require("./Jewelcrafter.png"),
  CrystalMine: require("./CrystalMine.png"),
  TreacherousLair: require("./TreacherousLair.png"),
  Reformatory: require("./Reformatory.png"),
  ElderTower: require("./ElderTower.png"),
  Mausoleum: require("./Mausoleum.png"),
  Dreamwood: require("./Dreamwood.png"),
  FearGauntlet: require("./FearGauntlet.png"),
  Theater: require("./Theater.png"),
};
